//! These functions are used in macro expansions when #[cfg(test)] is
//! enabled to test coverage of macro invocations in the unit tests.

pub fn actor_0() {}
pub fn actor_1() {}
pub fn actor_new() {}
pub fn actor_2() {}
pub fn actor_3() {}
pub fn actor_in_slab_0() {}
pub fn actor_in_slab_1() {}
pub fn actor_in_slab_2() {}
pub fn actor_in_slab_3() {}
pub fn query_0() {}
pub fn generic_call_0() {}
pub fn generic_call_1() {}
pub fn generic_call_2() {}
pub fn generic_call_3() {}
pub fn generic_call_4() {}
pub fn call_0() {}
pub fn call_1() {}
pub fn lazy_0() {}
pub fn lazy_1() {}
pub fn idle_0() {}
pub fn idle_1() {}
pub fn after_0() {}
pub fn after_1() {}
pub fn at_0() {}
pub fn at_1() {}
pub fn timer_max_0() {}
pub fn timer_max_1() {}
pub fn timer_min_0() {}
pub fn timer_min_1() {}
pub fn fwd_0() {}
pub fn fwd_1() {}
pub fn ret_0() {}
pub fn ret_1() {}
pub fn generic_fwd_0() {}
pub fn generic_fwd_1() {}
pub fn generic_fwd_2() {}
pub fn generic_fwd_3() {}
pub fn generic_fwd_4() {}
pub fn generic_fwd_5() {}
pub fn generic_fwd_6() {}
pub fn generic_fwd_7() {}
pub fn generic_fwd_8() {}
pub fn fwd_to_0() {}
pub fn fwd_to_1() {}
pub fn fwd_to_2() {}
pub fn fwd_panic_0() {}
pub fn fwd_do_0() {}
pub fn fwd_nop_0() {}
pub fn ret_to_0() {}
pub fn ret_to_1() {}
pub fn ret_to_2() {}
pub fn ret_to_3() {}
pub fn ret_some_to_0() {}
pub fn ret_some_to_1() {}
pub fn ret_some_to_2() {}
pub fn ret_do_0() {}
pub fn ret_some_do_0() {}
pub fn ret_panic_0() {}
pub fn ret_nop_0() {}
pub fn ret_shutdown_0() {}
pub fn ret_fail_0() {}
pub fn ret_fail_1() {}
pub fn ret_fail_2() {}
pub fn ret_failthru_0() {}
pub fn ret_failthru_1() {}
pub fn ret_failthru_2() {}
pub fn fail_0() {}
pub fn fail_1() {}
pub fn fail_2() {}
pub fn stop_0() {}
pub fn kill_0() {}
pub fn kill_1() {}
pub fn kill_2() {}
