#!/bin/bash

FEATURES="$1"

case "$FEATURES" in
    *no-unsafe*)
        ./workaround-for-test-threads cargo +nightly miri test __ $FEATURES || exit 1
        ;;
    *)
        echo "*** SKIPPING test that uses queue/flat.rs because MIRI no longer exposes vtable simulation ***"
        exit 0
        ;;
esac
