#!/bin/bash

# Install cargo-semver-checks first

if [ -z "$1" ]
then
    COMMAND="cargo semver-checks"
else
    COMMAND="cargo semver-checks --baseline-rev $1"
fi

./run-feature-combinations | while read FEATURES
do
    echo === $FEATURES

    FEAT="$(echo $FEATURES | perl -pe 's/--no-default-features/--only-explicit-features/; s/,/ --features /g;')"

    $COMMAND $FEAT || exit 1
done
