#!/bin/bash

# Maximise the number of combinations of features tested, rather than
# use the shorter combined list of features which minimises testing
# time.

./run-feature-combinations --max | while read FEATURES
do
    echo === $FEATURES
    cargo clippy $FEATURES
done
